## NumPY Array and Basics

In [1]:
import numpy as np

##  Creating array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([ [1, 2, 3], [4, 5, 6] ])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## List V/S numpy Array

In [ ]:
py_list = [1,2,3,4]
print("python list multplication", py_list * 2) 

np_array = np.array([1,2,3,4])
print("print python array multiplication", np_array * 2) # element wise multiplications

python list multplication [1, 2, 3, 4, 1, 2, 3, 4]
print python array multiplication [2 4 6 8]


## time

In [6]:
import time 
start = time.time()
py_list = [ i * 2 for i in range(10000)]
print('\n ist operation', time.time() - start)

start = time.time()
np_array = np.arange(100000) * 2
print("\n Numpy operation time", time.time() - start)


 ist operation 0.000982046127319336

 Numpy operation time 0.0005698204040527344


## Array from scratch

In [11]:
zeroes = np.zeros((3,4))
print(zeroes)

ones = np.ones( (2, 3))
print('once array', ones)

full = np.full( (2, 2), 7)
print("Full array", full)

random = np.random.random( (2, 3)) 
print("rando, array", random)

np_sequence = np.arange(0, 10, 2)
print("seqiqme array \n", np_sequence)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
once array [[1. 1. 1.]
 [1. 1. 1.]]
Full array [[7 7]
 [7 7]]
rando, array [[0.35331083 0.35947194 0.83238396]
 [0.81931185 0.25185593 0.98368471]]
seqiqme array 
 [0 2 4 6 8]


## Vector, Matrix and Tensor