## NumPY Array and Basics

In [26]:
import numpy as np

##  Creating array from list

In [27]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([ [1, 2, 3], [4, 5, 6] ])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## List V/S numpy Array

In [28]:
py_list = [1,2,3,4]
print("python list multplication", py_list * 2) 

np_array = np.array([1,2,3,4])
print("print python array multiplication", np_array * 2) # element wise multiplications

python list multplication [1, 2, 3, 4, 1, 2, 3, 4]
print python array multiplication [2 4 6 8]


## time

In [29]:
import time 
start = time.time()
py_list = [ i * 2 for i in range(10000)]
print('\n ist operation', time.time() - start)

start = time.time()
np_array = np.arange(100000) * 2
print("\n Numpy operation time", time.time() - start)


 ist operation 0.0003437995910644531

 Numpy operation time 0.0003018379211425781


## Array from scratch

In [30]:
zeroes = np.zeros((3,4))
print(zeroes)

ones = np.ones( (2, 3))
print('once array', ones)

full = np.full( (2, 2), 7)
print("Full array", full)

random = np.random.random( (2, 3)) 
print("random array", random)

np_sequence = np.arange(0, 10, 2)
print("sequence array \n", np_sequence)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
once array [[1. 1. 1.]
 [1. 1. 1.]]
Full array [[7 7]
 [7 7]]
random array [[0.24155296 0.43533634 0.88386496]
 [0.42176144 0.02923146 0.73763362]]
sequence array 
 [0 2 4 6 8]


## Vector, Matrix and Tensor

In [31]:
vector = np.array([1,2,3])
print("vector", vector)

matrix = np.array([[1,2,3], [4,5,6]])
print(matr ix)

tensor = np.array([ 
    [1,2],[3,4],[5,6],[7,8]
])  #multiple multidimantioanl
print('Tensor', tensor)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1339904077.py, line 5)

## ARRAY PROPERTIES

In [ ]:
arr = np.array([[1,3], [2,4]])

print("shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("Dtype", arr.dtype)


shape (2, 2)
Dimension 2
Size 4
Dtype int64


## ARRAY RESHAPING

In [ ]:
arr = np.arange(12) #create array with 12 elemne star with 0
print("origital array", arr)

reshape = arr.reshape((3,4)) #3 rows and 4 column
print('Resshaped Aray', reshape)

flattened = reshape.flatten() #returns copy
print('flattened Aray', flattened)

raveled = reshape.ravel() #ravel re̋turns view instead of copy
print('Raveled array', raveled)

#Transpose˝ 
transpose = reshape.T
print('tranpose', transpose)


NameError: name 'np' is not defined