## NUMpy Array Operations

In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5, 6, 7, 8, 9, 10])
print('Silcing', arr[2:7])
print('With steps', arr[1 : 8: 2])
print("Negative", arr[-3])

Silcing [3 4 5 6 7]
With steps [2 4 6 8]
Negative 8


In [5]:
## 2d array slicing

arr_2d = np.array( [  
                [ 1, 2, 3], 
                [ 4, 5, 6], 
                [ 7, 8, 9] 
            ])

print("specicifc element", arr_2d[1,2])
print("entire row", arr_2d[1]) #it target rows
print("entire col", arr_2d[:, 1]) #it target column


specicifc element 6
entire row [4 5 6]
entire col [2 5 8]


## SORTING

In [6]:
unsorted = np.array([4, 4, 8, 9, 1, 3, 6, 1, 0, 5, 2, 9])
print("Sorted array", np.sort(unsorted))

unsorted_arra_2d = np.array( [  
                    [3, 1], 
                    [1, 2], 
                    [2, 0]] 
                )

# axis=0 → sort column-wise (vertical)
# axis=1 → sort row-wise (horizontal)

print("Sorted 2D array by row", np.sort(unsorted_arra_2d, axis=1))

Sorted array [0 1 1 2 3 4 4 5 6 8 9 9]
Sorted 2D array by row [[1 3]
 [1 2]
 [0 2]]


## FILTER

In [7]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
evennum = numbers[numbers % 2 == 0] #num by allow to add expressiosn
print(evennum)



[ 2  4  6  8 10]


## Filter with Mask

In [8]:
mask = numbers > 5 #used expressions for evaluation
print("Numbers  greater than 5", numbers[mask])


Numbers  greater than 5 [ 6  7  8  9 10]


# Fancy indexing vs np.where()

In [9]:
indices = [0, 2, 4]
print(numbers[indices])

# np.where
where_result = np.where(numbers > 5)
print("np where", numbers[where_result])

[1 3 5]
np where [ 6  7  8  9 10]


In [10]:
data = np.array([10, 20, 30, 40, 50])
condition_array = np.where(data > 10, "True", "False") #if condition is true return "True" else "False"
print(condition_array)

['False' 'True' 'True' 'True' 'True']


## ADDING AND REMOVING Array

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#print(arr1 + arr2) #it will add element in the array

combine = np.concatenate( (arr1, arr2))
print(combine)

[1 2 3 4 5 6]


## Array Compatibility

In [14]:
a = np.array([1,2,3])
b = np.array([5,6,7,8])
c = np.array([7,8,9])

print("Compatability shapes", a.shape == b.shape)

Compatability shapes False


## Vstack and Hstack

In [21]:
original = np.array( [ [1, 2], [3,4] ])
new_row = np.array([ [5,6] ])
with_new_row = np.vstack((original, new_row)) #add a new row in original array
print(with_new_row)

new_col = np.array( [ [7], [8]])
with_new_col = np.hstack(( original, new_col)) #add a new colimn in the original array
print(with_new_col)

# Delete

myarr = np.array([ 1, 2, 3, 4,5,6])
deleted = np.delete(myarr, 2)
print('deleted', deleted)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]
deleted [1 2 4 5 6]
