## Practice Numpy  


In [2]:
import numpy as np

In [22]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

zeros = np.zeros( (2,3))
one = np.ones( (4,5) )

# Basic Operations

sum = a+b
print(sum)
print( a * b)
print( b - a)

print( a.mean())

[3 5 7 9]
[ 2  6 12 20]
[1 1 1 1]
2.5


## TASK

In [7]:
# Create a 5×5 array of zeros

array_zeros = np.zeros( (5, 5) )
array_range = np.arange(10, 16) #create from 10 to 15
print(array_zeros)
print(array_range)
print( array_range[:: -1])  #Reverse and array

print( array_range.max())
print( array_range.min() )
print( array_range.mean())
print( array_range.size )

reshaped_array = array_range.reshape(2,3)
print(reshaped_array)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[10 11 12 13 14 15]
[15 14 13 12 11 10]
15
10
12.5
6
[[10 11 12]
 [13 14 15]]


In [ ]:
#Broadcasting
arr = np.arange( 10,15 )
print(arr + 10 ) 

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([8,9,0])
col = np.array([ [1],  [2]])
print(arr_2d + col)

[20 21 22 23 24]
[[11 12 13]
 [24 25 26]]
